GreatSavings/Controllers/DealsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Data.Entity;

namespace GreatSavings.Controllers
{
    public class DealsController : ApiController
    {
        #region -- PRIVATE PROPERTIES --
        private GreatSavingsEntities db = new GreatSavingsEntities();

        #endregion


        // GET api/<controller>
        public IEnumerable<Deal> Get()
        {
            return db.Deals;
        }


        // GET api/<controller>/5
        public Deal Get(int id)
        {
            var deal = db.Deals.Where(t => t.TransId == id).FirstOrDefault();
            if (deal == null)
            {
                deal = new Deal();
            }

            return deal;
        }

        // GET api/<controller>
        [HttpGet]
        public HttpResponseMessage Load(int totalReturn, int skipRecord)
        {
            try
            {
               // var test = db.Deals.Include(i=>i.Transaction).ToList();
              
                var deals = db.Deals.ToList()
                            .Where(t => t.Transaction.PymtReceived == true && (t.ExpiryDate - DateTime.Now.Date).Days >= 0).AsEnumerable()
                            .Select(d => new { Image = System.Convert.ToBase64String(d.Image),
                                                Id = d.Id,
                                                CompanyName = d.Directory.CompanyName,
                                                Title = d.Title,
                                                ExpiryDate = d.ExpiryDate.ToString("dd MMM yyyy")
                            }).Skip(skipRecord).Take(totalReturn).OrderByDescending(d => d.ExpiryDate);

                
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK, deals);
                return response;
            }
            catch (Exception ex)
            {
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.NotImplemented, ex.Message);
                return response;
            }
        }

        // POST api/<controller>
        public HttpResponseMessage Post(Deal deals)
        {
            try 
            {
                db.Deals.Add(deals);
                db.SaveChanges();
                //foreach (Deal item in deals)
                //{
                //   // item.TransId = Convert.ToInt32(transactionId);
                //    db.Deals.Add(item);
                //    db.SaveChanges();
                //}
               
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK);
                return response;
            }
            catch (Exception ex)
            {
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.NotImplemented, ex.Message);
                return response;
            }
        }

        // POST api/<controller>
        [HttpPost]
        public HttpResponseMessage AddDeals(int transactionId, IEnumerable<Deal> deals)
        {
            try
            {
                foreach (Deal item in deals)
                {
                    item.TransId = transactionId;  // Convert.ToInt32(transactionId);
                    item.ExpiryDate = new DateTime(1900, 01, 01, 00, 00, 00);
                    db.Deals.Add(item);
                    db.SaveChanges();
                }

                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK);
                return response;
            }
            catch (Exception ex)
            {
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.NotImplemented, ex.Message);
                return response;
            }
        }

        // PUT api/<controller>/5
        public HttpResponseMessage Put(int id, Deal updatedItem)
        {
            try
            {
                var deal = db.Deals.Where(t => t.TransId == id).FirstOrDefault();
                if (deal == null)
                {
                    deal = updatedItem;
                    db.SaveChanges();
                }

                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK);
                return response;
            }
            catch (Exception ex)
            {
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.NotImplemented, ex.Message);
                return response;
            }
        }

        // DELETE api/<controller>/5
        public HttpResponseMessage Delete(int id)
        {
            try
            {
                Deal deal = new Deal {  Id = id };
                db.Deals.Attach(deal);

                db.Deals.Remove(deal);
                db.SaveChanges();

                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK);
                return response;
            }
            catch (Exception ex)
            {
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.NotImplemented, ex.Message);
                return response;
            }
        }
    }

}

GreatSavings/Controllers/DirectoryController.cs
using GreatSavings.Helper;
using GreatSavings.Models;
using GreatSavings.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using System.Linq;

namespace GreatSavings.Controllers
{
    public class DirectoryController : ApiController
    {
        #region -- PRIVATE PROPERTIES --
        private GreatSavingsEntities db = new GreatSavingsEntities();
        #endregion

        // GET api/<controller>
        public IEnumerable<Directory> Get()
        {
            return db.Directories;
        }

        // GET api/<controller>
        [System.Web.Http.HttpGet]
        public HttpResponseMessage GetByMerchant(int id)
        {
            try
            {
                var results = db.Directories.Where(d => d.Transaction.MerchantId == id)
                                             .Select(m => new { DirId = m.DirId, CompanyName = m.CompanyName });

                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK, results);
                return response;
            }
            catch (Exception ex)
            {
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.NotImplemented, ex.Message);
                return response;
            }
           
        }


        // GET api/<controller>/5
        public DirectoryViewModel Get(int id)
        {
            BusinessOperation bizOperations = new BusinessOperation();
            DirectoryViewModel directoryModel = new DirectoryViewModel();
            var directory = db.Directories.Where(t => t.TransId == id).FirstOrDefault();

            directoryModel.BusinessIndustries = db.BusinessIndustries.ToList().Select(b => new KeyValuePair<int, string>(b.BusIndustryId, b.BusIndustry)).ToList();
            directoryModel.Countries = db.Countries.ToList();
            directoryModel.States = db.States.ToList();
            directoryModel.OperatingHours = new SelectList(bizOperations.Hours);     // get the hours for business operation
            directoryModel.OperatingMinutes = new SelectList(bizOperations.Minutes); // get the minutes for business operation
            directoryModel.OperatingPeriod = new SelectList(bizOperations.Period);   // get the period for business operation

            if (directory == null)
            {
                directory = new Directory();
                directoryModel.Merchant.CompanyName = "Testing";
            }
            else
            {
                directoryModel.Merchant = directory;
            }
            return directoryModel;
        }

        // POST api/<controller>
        public HttpResponseMessage Post(Directory item)
        {
            try
            {
                db.Directories.Add(item);
                db.SaveChanges();
                
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK);
                return response;
            }
            catch (Exception ex)
            {
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.NotImplemented, ex.Message);
                return response;
            }
        }

        public HttpResponseMessage AddDirectories(int transactionId, IEnumerable<DirectoryViewModel> directoryList)
        {
            try
            {
                foreach (DirectoryViewModel item in directoryList)
                {
                    Directory newDirectory = item.Merchant;

                    newDirectory.TransId = transactionId;
                    db.Directories.Add(newDirectory);
                    db.SaveChanges();
                }

                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK);
                return response;
            }
            catch (Exception ex)
            {
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.NotImplemented, ex.Message);
                return response;
            }
        }

        // GET api/<controller>/GenerateId/PG
        [System.Web.Http.HttpGet, System.Web.Http.ActionName("GenerateId")]
        public HttpResponseMessage GenerateId(string id)
        {
            try
            {
                int randNum = DataManager.GetRandonNum();

                string newMerhantID = string.Concat(id, randNum);

                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK, newMerhantID);
                return response;
            }
            catch (Exception ex)
            {
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.NotImplemented, ex.Message);
                return response;
            }
        }

        // PUT api/<controller>/5
        public HttpResponseMessage Put(int id, Directory updatedItem)
        {
            try
            {
                var directory = db.Directories.Where(t => t.TransId == id).FirstOrDefault();
                if (directory == null)
                {
                    directory = updatedItem;
                    db.SaveChanges();
                }

                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK);
                return response;
            }
            catch (Exception ex)
            {
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.NotImplemented, ex.Message);
                return response;
            }
        }

        // DELETE api/<controller>/5
        public HttpResponseMessage Delete(string id)
        {
            try
            {
                Directory directory = new Directory { DirId = id };
                db.Directories.Attach(directory);

                db.Directories.Remove(directory);
                db.SaveChanges();

                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK);
                return response;
            }
            catch (Exception ex)
            {
                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.NotImplemented, ex.Message);
                return response;
            }
        }
    }
}

GreatSavings/Controllers/ProductSubmissionController.cs
using GreatSavings.Helper;
using GreatSavings.Models;
using GreatSavings.ViewModels;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
//using System.Web.Http;
using System.Web.Mvc;

namespace GreatSavings.Controllers
{
    public class ProductSubmissionController : Controller
    {
        private GreatSavingsEntities db = new GreatSavingsEntities();
        //
        // GET: /ProductSubmission/
        public ActionResult Index()
        {
            var products = db.Products.Where(p => p.Payable == true);
            return View(products.ToList());
        }

        public ActionResult ProductList()
        {
            var products = db.Products.Where(p => p.Payable == true);

            var settings = new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() };
            string jsonString = JsonConvert.SerializeObject(products, Formatting.None, settings);

            return View((object)jsonString);
        }

        [HttpPost]
        public ActionResult ProductList(FormCollection form)
        {
            try
            {
                // TODO: Add insert logic here
                Session["SelectedProducts"] = form["selectedProducts"];
                return RedirectToAction("Subscribe");
                //return RedirectToAction("Login", "Account");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ProductSubmission/Deals/
        public ActionResult Deals()
        {
            return View();
        }

        //
        // GET: /ProductSubmission/Directory/
        public ActionResult Directory()
        {
            return View();
        }

        //
        // GET: /ProductSubmission/Directory/
        public ActionResult LoadDirectoryModel()
        {
            BusinessOperation bizOperations = new BusinessOperation();
            DirectoryViewModel merchantModel = new DirectoryViewModel();

            merchantModel.BusinessIndustries = db.BusinessIndustries.ToList().Select(b => new KeyValuePair<int, string>(b.BusIndustryId, b.BusIndustry)).ToList();
            merchantModel.Countries = db.Countries.ToList();
            merchantModel.States = db.States.ToList();
            merchantModel.OperatingHours = new SelectList(bizOperations.Hours);     // get the hours for business operation
            merchantModel.OperatingMinutes = new SelectList(bizOperations.Minutes); // get the minutes for business operation
            merchantModel.OperatingPeriod = new SelectList(bizOperations.Period);   // get the period for business operation          
            merchantModel.Merchant.CompanyName = "Testing";
            return Json(merchantModel, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /ProductSubmission/Directory/
        public ActionResult LoadDealModel()
        {
            Deal dealModel = new Deal();
         
            dealModel.Title = "Testing";
            // return PartialView(merchantModel);
            return Json(dealModel, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /ProductSubmission/OpeningModel/
        public ActionResult LoadNewOpeningModel()
        {
            NewOpening newOpeningModel = new NewOpening();

            newOpeningModel.Description = "Testing";
            // return PartialView(merchantModel);
            return Json(newOpeningModel, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /ProductSubmission/Recommendation/
        public ActionResult LoadRecommendationModel()
        {
            Recommendation recommendationModel = new Recommendation();

            recommendationModel.Description = "Testing";
            // return PartialView(merchantModel);
            return Json(recommendationModel, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /ProductSubmission/Advertisement/
        public ActionResult LoadAdvertisementModel()
        {
            Advertisement advertisementModel = new Advertisement();

            advertisementModel.ExpiryDate = DateTime.Now;
            // return PartialView(merchantModel);
            return Json(advertisementModel, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /ProductSubmission/Create
        public ActionResult Subscribe()
        {
            if (Session["SelectedProducts"] != null)
            {
                // Step 1: get the services selected from session 
                string jsonString = Session["SelectedProducts"].ToString();

                // Step 2: load the partial view 
                return View((object)jsonString);
            }
            else
            {
                return View();
            }
        }

        //
        // GET: /ProductSubmission/Create
        public ActionResult Promotion()
        {
           
                return View();
            
        }

        //
        // GET: /ProductSubmission/Create
        public ActionResult GetForm(int productId)
        {
            switch  (productId)
            {
                case 0:
                    return PartialView("~/Views/Account/Register.cshtml");
                case 1: // Adevertisement

                case 2:   // Deals
                    // load the partial view 
                    return PartialView("~/Views/ProductSubmission/Deals.cshtml");
                case 3:   // Directory Listing
                    // load the partial view 

                   //return RedirectToAction("Directory");
                   return PartialView("~/Views/ProductSubmission/Directory.cshtml");
                case 4: // New Opening
                   // load the partial view 
                   return PartialView("~/Views/ProductSubmission/NewOpening.cshtml");
                case 5: // Recommendation
                   // load the partial view 
                   return PartialView("~/Views/ProductSubmission/Recommendation.cshtml");
                default:
                    return View();
            }
        }


    }
}

GreatSavings/Views/ProductSubmission/Deals.cshtml
<link href="~/Content/bootstrap-datepicker3.css" rel="stylesheet" />


<div class="form-title" >
    <h3>Create Deals</h3>
</div>
<form name="dealsForm"  ng-controller="subscriptionController" ng-init="loadModel(2)" novalidate valid-submission="update($event)">  
    <div class="form-horizontal">    
        <div id="entry-list" style="float:left" ng-show="orderQty > 1">
            <ul class="nav nav-tabs nav-tabs2" id="myTab">
                <li>
                    <label>&nbsp</label>
                </li>
                <li ng-repeat="i in listings track by $index" ng-class="{'active-wbg': $index == currentIndex }">
                   @* ng-class="$index == 0 ? 'active-wbg' : ''"*@ 
                     <a href="#tab{{$index+1}}" ng-click="getSelectedForm(dealsForm, $index)">Deals {{$index+1}}</a>
                </li>
            </ul>
        </div>   
        <div id="form-leftSection" > 
           <merchant-selector datasource="$parent.merchants" ng-model="model.DirId" 
                invalid="dealsForm.$submitted && dealsForm.merchant.$error.required"></merchant-selector>  
            <div class="form-group">
                <label class="control-label col-xs-2">Title</label>
                <div class="col-xs-10">
                    <input ng-model="model.Title" class="form-control" name="title" required validation-style />
                    <validation-error has-error="dealsForm.$submitted && dealsForm.title.$error.required" show-icon="true"
                        error-message="The title is required"></validation-error>              
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-xs-2">Description</label>
                <div class="col-xs-10">
                    <textarea ng-model="model.Description" class="form-control" rows="6" name="description" required validation-style  />
                    <validation-error has-error="dealsForm.$submitted && dealsForm.description.$error.required" show-icon="true"
                        error-message="The description is required"></validation-error>    
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-xs-2">Terms and Condition</label>
                <div class="col-xs-10">
                    <textarea ng-model="model.TermsAndCondition" class="form-control" rows="6" name="termsAndCondition" required validation-style />
                    <validation-error has-error="dealsForm.$submitted && dealsForm.termsAndCondition.$error.required" show-icon="true"
                        error-message="The description is required"></validation-error>    
                </div>
            </div>
          @*  <div class="form-group">
                <label class="control-label col-xs-2" >Expiry Date</label>
                <div class="col-xs-10">
                   <div class='input-group date' id='expiryDatePicker'>
                        <input id="deal_exp_date" type='text'" class="form-control" ng-model="model.ExpiryDate"/>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
         
                </div>
            </div>*@
            <div class="form-group">
                <input type="file" ng-model="model.uploadedImage" selected-image="model.Image" name="dealsImage" id="dealsImageUploader" class="hdn" 
                    accept='image/*' image-file-reader required/>
                <label class="control-label col-xs-2">Deals Picture</label>
                <div class="col-xs-10">
                    <label style="font-weight: normal;margin-top: 8px;">Max. file size: 8 MB. Allowed images: jpg, gif, png.</label><br />
                    <div image-picker  file-uploader="dealsImageUploader" uploaded-image="model.uploadedImage"></div>
                    <validation-error has-error="dealsForm.$submitted && dealsForm.dealsImage.$error.required" show-icon="false"
                        error-message="The picture is required"></validation-error>   
                </div>
            </div>
        </div>
   @*     <div id="form-rightSection">
            <div class="form-group">
                  
                  <span>Max. file size: 8 MB. Allowed images: jpg, gif, png.</span><br />
            
        </div>  
    </div> *@
        </div>
    <div class="form-update">
        <input id="btnDirContinue" type="button" value="Continue" class="btn btn-large btn-primary btn-r-pos btn-subs continue" 
            ng-click="saveAll($event)" ng-disabled="completed == false"  />
         &nbsp
         @*<input id="btnDirUpdate" type="button" value="Update" class="btn btn-large btn-primary btn-r-pos btn-subs" ng-click="update($event)"/>*@
        
        <button id="btnDealsUpdate" class="btn btn-large btn-primary btn-r-pos btn-subs action" type="submit" >
	        <i class="act-indicator i-M-loader"></i>
	        <i class="act-indicator i-accept"></i>
	        <i class="act-indicator i-ignore"></i>
	        <span><b>Update</b></span>
        </button>
    </div>
</form>

GreatSavings/Views/ProductSubmission/Index.cshtml
@model IEnumerable<GreatSavings.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="../../Content/admin.css" rel="stylesheet" />


<div class="pricing-table group">
    <h1 class="heading">
        Pricing overview
    </h1>
    @foreach (var item in Model) {    
        <div class="price-block fl @(item.Name.Replace(' ', '-').ToLower())">
            <h2 class="title">@Html.DisplayFor(modelItem => item.Name)</h2>
            <!-- CONTENT -->
            <div class="content">
                <p class="price">
                    <sup>RM</sup>
                    <span>@(item.Price.ToString("F0", System.Globalization.CultureInfo.InvariantCulture))</span>
                </p>
                <p class="hint">@Html.DisplayFor(modelItem => item.Hint)</p>
            </div>
            <!-- /CONTENT -->
            <!-- FEATURES -->
            <div class="features">
               @Html.DisplayFor(modelItem => item.Description)
            </div>
            <!-- /FEATURES -->
            <!-- PT-FOOTER -->
            <div class="pt-footer">
                <input type="submit" value="Buy Now" class="btn" />
            </div>
            <!-- /PT-FOOTER -->
        </div>
    }

</div>

GreatSavings/Views/ProductSubmission/ProductList.cshtml
@model string


@{
    ViewBag.Title = "ProductList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/Services/productservices.js" type="text/javascript"></script>
<script src="~/Scripts/Controllers/productcontroller.js" type="text/javascript"></script>

<script type="text/javascript">    

 @*   bizModule.factory("productFactory", function () {
        var fac = {};
        fac.getProducts = function () { return  @Html.Raw(Model); }
        return fac;
    });*@

</script>  
@*  <ul>
        <li><a href="/#/RDeals">Deals</a></li>
        <li><a href="/#/RDirectory">Directory</a></li>
    </ul>
<div ng-view></div>*@
@using (Html.BeginForm("ProductList", "ProductSubmission", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="pricing-table group" ng-controller="productController" ng-init="getProducts(@Html.Raw(Model))">
        <h1 class="heading">
            Pricing overview
        </h1>
        <div ng-repeat="item in products" class="price-block buy fl {{ item.name.replace(' ', '-').toLowerCase() }}">
            <h2 class="title">{{ item.name }} </h2>
            <!-- CONTENT -->
            <div class="content">
                <p class="price">
                    <sup>RM</sup>
                    <span>{{ item.price }}</span>
                </p>
                <p class="hint">{{ item.hint }}</p>
            </div>
            <!-- /CONTENT -->
            <!-- FEATURES -->
            <div class="features">
                {{item.description }}
            </div>
            <!-- /FEATURES -->
            <!-- PT-FOOTER -->
            <div class="pt-footer">
               @* <input type="button" value="Buy Now" class="btn" ng-click="addToCart(item)" />*@
                <input type="button" value="Buy Now" class="btn" ng-click="addToCart($index)" ng-hide="item.selected" />
               @* <label class="cartTick" ng-show="item.selected" ng-click="removeFromCart($index)">&nbsp</label>*@
                 <label class="cartTick" ng-show="item.selected" ng-click="removeItemFromCart($index)">&nbsp</label>
            </div>
            <!-- /PT-FOOTER -->
        </div>
        <div class="cart-wrapper">
          <span id="shopping-cart-counter">{{itemsInCart.length}}</span>
          <i id="cartimg" class="shopping-cart" style=""></i>
        </div>

        <p class="center-elmnt">
            <input type="submit" value="Continue" class="btn" ng-disabled="itemsInCart.length == 0" ng-click="subscribe()" 
                style="background-color: #5794db;color: #fff;width: 180px;">

        </p>

        @*<div class="cart">
            <h2 class="title">
                <div class="cart-ico-wrapper"><i class="shopping-cart"></i></div>
                Shopping Cart

            </h2>
     
            <ul class="cart-items">
                <li ng-repeat="item in itemsInCart" class="product"  >
                    <div class="fleft">
                        <a href="#" ng-click="removeFromCart($index)">
                            <img src="~/Images/blank.gif" />
                        </a> 
                        <div>{{item.product }}</div>
                    </div>
                    <div class="fright tag {{ item.product.replace(' ', '-').toLowerCase() }}">
	                    <a href="#">RM&nbsp{{item.price }}</a>
                    </div>
                </li>
            </ul>
            <div class="cart-total">
                <h3>Total Purchase</h3>
                <p class="price">
                    <sup>RM</sup>
                    <span class="ng-binding">{{totalPrice}}</span>
                </p>
                <p>
                    <input type="submit" value="Continue" class="btn"  ng-disabled="itemsInCart.length == 0" ng-click="subscribe()"/>
                </p>
            </div>        
        </div>*@
    </div>
    <input type="hidden" value="hidden" id ="selectedProducts" name="selectedProducts" />
}
  